apiVersion: v1
kind: Service
metadata:
  name: react-demo-app
  namespace: java-demoapp-namespace
  labels:
    app.kubernetes.io/name: react-demo-app
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: react-demo-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000